### ISSUE TITLE
Live preview

### ISSUE THREAD

**Issue by diniamo** [Qalculate/libqalculate#659]
The only feature I'm missing from qalculate is a proper live preview. The gui version (at least the qt one) has something like that, but the problem is that it's a popup window that disappears after some time, instead of being a part of the gui. I like using the terminal interface more anyway, so I'd like something like what fend has.

I have one question for the unlikely scenario in which I try to implement this myself: should it be enabled by default?

<br>
Showcase of fend:

https://github.com/Qalculate/libqalculate/assets/55629891/57fa3c50-5fe2-4fe8-a96b-5f0767f0105f

**Comment by hanna-kn** [comment]
> The gui version (at least the qt one) has something like that, but the problem is that it's a popup window that disappears after some time, instead of being a part of the gui.

This is not true for the GTK UI, and the tooltip variant in the QT UI can be made more persistent by removing the delay (using expression context menu or in preferences).

**Comment by diniamo** [comment]
Ah you're right, I didn't consider the gtk one, because it looks way uglier with the huge buttons. And it still gets removed in the qt one if the window loses focus.

**Comment by hanna-kn** [comment]
At the moment I do not know how to implement a "live preview" in the CLI, but if I'm able to find a feasible solution I will add it as an option.

> Ah you're right, I didn't consider the gtk one, because it looks way uglier with the huge buttons.

The buttons, as well as all other non-essential GUI elements (see https://qalculate.github.io/images/qalculate-main-window.png), can be hidden.

**Comment by hanna-kn** [comment]
Done.

It is disabled by default (for now) and can be activated using `set autocalc` or `set calculate as you type` (the option name is not finalized and I'm open to suggestions).

Note also that the "live preview" in the Qt UI has been updated and is now shown in the result list by default.

**Comment by diniamo** [comment]
Whoa, thanks a lot. I'll close the issue as soon as I've tested the commit, or you can do so before, if you see fit. Gonna need to figure out how to set persistent options for that, since I haven't done it before.

**Comment by diniamo** [comment]
Works well. There is a small delay, but I assume that can't easily be fixed(?)

**Comment by diniamo** [comment]
@hanna-kn it looks like there are bugs. For example, if I quickly update the expression, and press enter before the preview updates, it gets messed up:
![image](https://github.com/user-attachments/assets/5358c428-adb3-4c82-b5ef-83323bb15237)
![image](https://github.com/user-attachments/assets/ca1a6f5a-16ef-4e22-8392-1828075c9cf7)

**Comment by hanna-kn** [comment]
I'm not noticing any obvious delay. It is difficult for me to be able to press enter before the preview is updated, but the latest commit should fix the the bug.

Bugs are expected at this stage.

**Comment by diniamo** [comment]
Looking at the code, it seems like you flush at the end of the `clear_autocalc` function, which isn't ideal, since that will cause the space to be empty until the next flush with the final result happens (this visually results in a flash). Wouldn't it be possible to simply remove the first flush, or to avoid it some other way?

**Comment by diniamo** [comment]
Looks like I missed something, the flash still happens, even if I remove the flush call.

**Comment by howaboutuser** [comment]
`It is difficult for me to be able to press enter before the preview is updated`
Copy (including newline character) and paste should produce this issue (maybe?)

**Comment by diniamo** [comment]
Just tested the latest commit, seems to work perfectly now. Closing.

**Comment by diniamo** [comment]
Now that I got a notification, I also have an issue: using ans is completely broken with autocalc enabled. For example
```
> 1+1

  1 + 1 = 2

> ans+1
```
if in this example, instead of pressing enter, you remove and add the 1 at the end, the result doesn't get reset, and now you actually get +2. It's also not reset when actually sending the prompt, so if I do `ans+1` and press enter, I will actually get `ans+2` as the result (while it still says `ans+1`).

**Comment by hanna-kn** [comment]
> I don't seem to be able to enable this via ~/.config/qalculate/qalc.cfg with autocalc=1 under [General] or [Mode]

`calculate_as_you_type`, not `autocalc` is used in the configuration file. The location of the option does not matter.

> Is it currently possible to make it persistent?

It should normally be saved automatically on exit, unless `save mode` is disabled.

**Comment by hanna-kn** [comment]
> Now that I got a notification, I also have an issue: using ans is completely broken with autocalc enabled.

This issue has been reported in https://github.com/Qalculate/libqalculate/issues/722 and fixed in commit https://github.com/Qalculate/libqalculate/commit/0d81784d2c85ca90b5a660b70862b9572be661e3.

**Comment by isosphere** [comment]
> `calculate_as_you_type`, not `autocalc`, is used in the configuration file. The location of the option does not matter.

I had that in there already set to `-1`, now set to `1` and working as expected. Thank you.

> It should normally be saved automatically on exit, unless `save mode` is disabled.

I did have `save mode` disabled but had forgotten; I find myself often switching between sexagesimal and other display modes and prefer a consistent startup state. 

Thank you for the response and for your work on the project, you've made a useful calculator.

**Comment by diniamo** [comment]
> This issue has been reported in #722 and fixed in commit [0d81784](https://github.com/Qalculate/libqalculate/commit/0d81784d2c85ca90b5a660b70862b9572be661e3).

Thanks, I should've tried updating first

**Comment by azizsayfiddin** [comment]
Is there a way to make time calculations auto updated? So, I don't have delete and type again to see time changes.
