### ISSUE TITLE
stats.batch: vector test fails (runtime error: index -1 out of bounds for type 'vector [20]')

### ISSUE THREAD

**Issue by csfore** [Qalculate/libqalculate#853]
Test Output:
```
Mismatch detected at line 25
mean(libqalculate_tests_vector)
expected '6.530919283'
received '(2.348595500E-16 / [(10.00000000 t*s*m^2)]) B*t^2*m^3*s^3'
```

When trying to load the file directly:
```
> libqalculate_tests_vector=load(tests/vectordata.csv)

  warning: Did you mean "teslas" (instead of "tests")?
  error: "v" is not a valid variable/function/unit.
  warning: To avoid division by zero, the following must be true: [(10000000 g·s·m²)] ≠ 0.
  save(liter·byte·attoday × ((tonne × e second·tonne·seconds) / [dot(decatonne·are, centisecond)]),
  libqalculate_tests_vector, Temporary, , 1) ≈
  (2.348595500E−16 / [(10.00000000 t·s·m²)]) B·t²·m³·s³
```

When built with `CXXFLAGS="-O2 -g -fsanitize=address -fsanitize=undefined"`
```
$ ./src/qalc "libqalculate_tests_vector=load(tests/vectordata.csv)"
Calculator-parse.cc:3446:61: runtime error: index -1 out of bounds for type 'vector [20]'
    #0 0x7f89ad44a705 in Calculator::parse(MathStructure*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ParseOptions const&) /home/csfore/w/repos/libqalculate/libqalculate/Calculator-parse.cc:3446
    #1 0x7f89ad459ec1 in Calculator::parse(MathStructure*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ParseOptions const&) /home/csfore/w/repos/libqalculate/libqalculate/Calculator-parse.cc:3203
    #2 0x7f89ad427714 in Calculator::parse(MathStructure*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ParseOptions const&) /home/csfore/w/repos/libqalculate/libqalculate/Calculator-parse.cc:1531
    #3 0x7f89ad6d5cc2 in Calculator::calculate(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, EvaluationOptions const&, MathStructure*, MathStructure*, bool) /home/csfore/w/repos/libqalculate/libqalculate/Calculator-calculate.cc:3677
    #4 0x7f89ad6ef355 in CalculateThread::run() /home/csfore/w/repos/libqalculate/libqalculate/Calculator-calculate.cc:84
    #5 0x7f89adc0878a in Thread::doRun(void*) /home/csfore/w/repos/libqalculate/libqalculate/util.cc:1161
    #6 0x7f89b1e63eb7  (/usr/lib/gcc/x86_64-pc-linux-gnu/16/libasan.so.8+0x63eb7)
    #7 0x7f89a90c2084  (/usr/lib64/libc.so.6+0x99084)
    #8 0x7f89a9137eeb  (/usr/lib64/libc.so.6+0x10eeeb)
```

I tried this on the commit that the `tests/vectordata.csv` file was added and the same error occurred.

Built with: GCC 13 and GCC 16.

**Comment by hanna-kn** [comment]
Fixed.

**Comment by csfore** [comment]
I no longer get the sanitizer error but I still get this error:
```
$ ./src/qalc "libqalculate_tests_vector=load(tests/vectordata.csv)"
warning: Did you mean "teslas" (instead of "tests")?
error: "v" is not a valid variable/function/unit.
warning: To avoid division by zero, the following must be true: [(10000000 g·s·m²)] ≠ 0.
save(liter·byte·attoday × ((tonne × e second·tonne·seconds) / [dot(decatonne·are, centisecond)]), "libqalculate_tests_vector", "Temporary", "", 1) ≈ (2.348595500E−16 / [(10.00000000 t·s·m²)]) B·t²·m³·s³
```

**Comment by hanna-kn** [comment]
Fixed, assuming that you compiled libqalculate with `--disable-insecure` configure option which disables the `load` function.

**Comment by csfore** [comment]
Thanks! That fixed it. Would it be possible to have it output something along the lines of `This function is disabled when --disable-insecure is specified` whenever one of those functions are called?

**Comment by hanna-kn** [comment]
> Would it be possible to have it output something along the lines of This function is disabled when --disable-insecure is specified whenever one of those functions are called?

Done.
